# Generated by Django 5.0.4 on 2024-06-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_siret', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_securite_sociale', models.CharField(max_length=15)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('cfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.cfa')),
                ('invite_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants_invites', to='etudiants.cfa')),
            ],
        ),
    ]
